In [1]:
using Random, Distributions
using Plots
# plotlyjs()
# using PlotlyJS
using DataFrames
using StatsBase
using DelimitedFiles
using LinearAlgebra
# using Distances
# using Symbolics
# using Latexify

# Problem Set 5 (Jonathan Fischer using Julia)

## 1) Langevin Dynamics of minimalist HP 

### Initialize Positions R

In [2]:
function initR()
    R = zeros((5,3))
    R[:,3] .= 1,2,3,4,5
    R
end

initR (generic function with 1 method)

In [11]:
initR()

5×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  0.0  2.0
 0.0  0.0  3.0
 0.0  0.0  4.0
 0.0  0.0  5.0

### Calculate distance (single component)

In [3]:
function calc_dist(x1,x2) #calculate distance between a single pair of points along single component
    x1-x2 
    # dx - L*round(dx/L) #distance using minimum image convention 
end

calc_dist (generic function with 1 method)

### Calculate non-bonded potential 

In [4]:
function calc_LJ(r, epsilon, sigma = 1) # calculate Lennard_Jones potential for a pairwise distance
    4*epsilon*((sigma/r)^12 - (sigma/r)^6) 
end

calc_LJ (generic function with 2 methods)

### Calculate force (dU + friction + noise) returns tuple of force terms

In [142]:
function calc_LJforce(r, epsilon, T, v, dt, sigma = 1, k=1, m=1, eta=0.05)
    # (48*epsilon*((sigma^12/r^13)-0.5*(sigma^6/r^7)) + randn()*√(2kT*m*eta/dt) - eta*m*v, 
    [48*epsilon*((sigma^12/r^13)-0.5*(sigma^6/r^7)),
    randn()*√(2k*T*m*eta/dt),
    -(eta*m*v)]
end

calc_LJforce (generic function with 5 methods)

### Calculate bonded potential

In [6]:
function calc_harmU(r,k=20,l=1)
    0.5k*(r-l)^2
end

calc_harmU (generic function with 3 methods)

### Calculate bond force

In [131]:
function calc_harmforce(r,k=20,l=1)
    k*(r-l),0.,0.
end

calc_harmforce (generic function with 3 methods)

### Update acceleration matrix A

In [154]:
function update_A(R, T, V, dt, m = 1) #update distance matrix D and acceleration matrix A 
    PE = 0 #initialize potential energy
    N = length(R[:,1])
    A = zeros((N,3))
    for i in 1:N-1
        for j in i+1:N
            dr = calc_dist.(R[i,:],R[j,:]) #calculate distance vector between two points
            r_mag = norm(dr) #calculate magnitude of distance vector
            if j - i > 1
                if (i,j) == (1,4) || (i,j) == (1,5) || (i,j) == (4,5)
                    epsilon = 1.
                    PE += calc_LJ(r_mag, epsilon)  #accumulate LJ potential energy
                    # f_scalars = calc_LJforce(r_mag,epsilon,T,v,dt) #scalar magnitude of force
                    A[i,:] += [x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[i]),dt)] #force vector with each component
                    A[j,:] -= [x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[i]),dt)] #force vector with each component
                else
                    epsilon = 2/3
                    PE += calc_LJ(r_mag, epsilon)  #accumulate LJ potential energy
                    A[i,:] += [x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[i]),dt)] #force vector with each component
                    A[j,:] -= [x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[j]),dt)] #force vector with each component
                end
            else 
                PE += calc_harmU(r_mag)
                # fvector = [x * dr/ r_mag for x in calc_harmforce(r_mag)]
                fvector = calc_harmforce(r_mag).*dr/r_mag
                # return fvector
                A[i,:,:] .+= fvector
                A[j,:,:] .-= fvector
            end
        end
    end
    return PE, A
end

update_A (generic function with 3 methods)

In [171]:
dt = 0.003
T = 2.
PE = 0 #initialize potential energy
N = length(R[:,1])
V = init_velocity(T,N) #velocity for t
A = zeros((N,3,3))
# A = Matrix(Vector{Float64})(undef, (N,3))
for i in 1:N-1
    for j in i+1:N
        dr = calc_dist.(R[i,:],R[j,:]) #calculate distance vector between two points
        r_mag = norm(dr) #calculate magnitude of distance vector
        if j - i > 1
            if (i,j) == (1,4) || (i,j) == (1,5) || (i,j) == (4,5)
                epsilon = 1.
                PE += calc_LJ(r_mag, epsilon)  #accumulate LJ potential energy
                # f_scalars = calc_LJforce(r_mag,epsilon,T,v,dt) #scalar magnitude of force
                A[i,:,:] += [x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[i]),dt)] #force vector with each component
                A[j,:,:] -= [x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[i]),dt)] #force vector with each component
            else
                epsilon = 2/3
                PE += calc_LJ(r_mag, epsilon)  #accumulate LJ potential energy
                A[i,:,:] += [x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[i]),dt)] #force vector with each component
                A[j,:,:] -= [x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[j]),dt)] #force vector with each component
            end
        else 
            PE += calc_harmU(r_mag)
            # fvector = [x * dr/ r_mag for x in calc_harmforce(r_mag)]
            fvector = calc_harmforce(r_mag).*dr/r_mag
            # return fvector
            A[i,:,:] .+= fvector
            A[j,:,:] .-= fvector
        end
    end
end

LoadError: DimensionMismatch: dimensions must match: a has dims (Base.OneTo(3), Base.OneTo(3)), must have singleton at dim 2

In [168]:
randn((3,3))

3×3 Matrix{Float64}:
 1.86221   1.03084    0.33084
 1.46432  -0.161977   2.49733
 1.42788  -1.0537    -0.562378

In [166]:
A[1,:,:] =  randn((3,3))

3×3 Matrix{Float64}:
 -0.45967    -0.0598998  -0.290438
 -0.620965   -1.30737     0.277781
  0.0907327   0.146263    0.377251

In [167]:
A

5×3×3 Array{Float64, 3}:
[:, :, 1] =
 -0.45967  -0.620965  0.0907327
  0.0       0.0       0.0
  0.0       0.0       0.0
  0.0       0.0       0.0
  0.0       0.0       0.0

[:, :, 2] =
 -0.0598998  -1.30737  0.146263
  0.0         0.0      0.0
  0.0         0.0      0.0
  0.0         0.0      0.0
  0.0         0.0      0.0

[:, :, 3] =
 -0.290438  0.277781  0.377251
  0.0       0.0       0.0
  0.0       0.0       0.0
  0.0       0.0       0.0
  0.0       0.0       0.0

In [170]:
[x * dr / r_mag for x in calc_LJforce(r_mag,epsilon,T,norm(V[2]),dt)]

LoadError: UndefVarError: epsilon not defined

In [121]:
R = initR() # 5x3 Matrix{Float64}
dr = calc_dist.(R[1,:],R[3,:])
r_mag = norm(dr) #scalar

2.0

In [66]:
R 

5×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  0.0  2.0
 0.0  0.0  3.0
 0.0  0.0  4.0
 0.0  0.0  5.0

In [93]:
test = [3;9;7]


3-element Vector{Int64}:
 3
 9
 7

In [92]:
dr .* test

3-element Vector{Float64}:
   0.0
   0.0
 -14.0

In [120]:
r_mag

2.0

In [132]:
# dr = [1,4,2]
# r_mag = 5
# fvector = [x * dr/ r_mag for x in calc_harmforce(r_mag)]
fvector  = calc_harmforce(r_mag)#/r_mag # fvector is Vector{Float64}
# for comp in fvector
#     comp*dr/r_mag
# end
    
    



(20.0, 0.0, 0.0)

In [127]:
fvector

0.0

In [129]:
calc_harmforce(r_mag)

(20.0, 0.0, 0.0)

In [130]:
typeof(fvector)

Float64

In [98]:
println('typeof($(r_mag) typeof(dr) typeof(fvector)'))

LoadError: LoadError: UndefVarError: @typeof_str not defined
in expression starting at In[98]:1

In [42]:
A = zeros((30,3,3))

30×3×3 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 ⋮         
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 ⋮         
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0

In [139]:
A[1,:,:] .+= fvector

3×3 view(::Array{Float64, 3}, 1, :, :) with eltype Float64:
 40.0  40.0  40.0
  0.0   0.0   0.0
  0.0   0.0   0.0

In [138]:
A

30×3×3 Array{Float64, 3}:
[:, :, 1] =
 20.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  ⋮         
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0

[:, :, 2] =
 20.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  ⋮         
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0

[:, :, 3] =
 20.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.0
  0.0  0.0  0.

In [32]:
test = [[1,2,3];;[4,5,6];;;[7,8,9];;[4,7,4]]

3×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  4
 2  5
 3  6

[:, :, 2] =
 7  4
 8  7
 9  4

In [86]:
r_mag = 2
dr = [1,2,3]

fvector = [x * dr/ r_mag for x in calc_harmforce(r_mag)]


3-element Vector{Vector{Float64}}:
 [10.0, 20.0, 30.0]
 [0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0]

In [87]:
calc_harmforce(r_mag)

3-element Vector{Int64}:
 20
  0
  0

### Calculate new position {vector}

In [9]:
function calc_position(r, v, a, dt) #update position vector for single particle
    r + (v*dt) + 0.5(a*dt^2)
end

calc_position (generic function with 1 method)

### Update position matrix R in place (V,A,dt)

In [10]:
function update_R!(R, V, A, dt) #updates position matrix R IN PLACE
    broadcast!(calc_position,R,R,V,A,dt) #vectorized operation passed R by reference 
end

update_R! (generic function with 1 method)

### Calculate velocity {v::float, a1::float, a2::float, dt::float} with BBK

In [11]:
function calc_velocity(v,a1,a2,dt,eta=0.05) #velocity verlet update of velocity for single component
    (1+dt*eta/2)^-2 * (v + 0.5(a1)*dt + 0.5(a2[1] + a2[2])*dt) #average current and new accelerations
end

calc_velocity (generic function with 2 methods)

### Update velocity matrix V (V,A1,A2,dt)

In [12]:
function update_V!(V,A1,A2,dt) #updates velocity matrix V IN PLACE (passed by reference)
    broadcast!(calc_velocity,V,V,A1,A2,dt)
end

update_V! (generic function with 1 method)

### Initialize velocity (T,N,m,k)

In [13]:
function init_velocity(T, N, m=1, k=1) #temperature, count, and mass
    V = √(k*T/m)*randn((N,3)) #return N x 3 matrix of initialized velocities sampled from Maxwell-Boltzmann distribution
    V[end,:] = -sum(V[1:end-1,:],dims=1) #Momentum conservation: last row equals minus sum of all other rows. Mass cancels out because same species 
    return V
end

init_velocity (generic function with 3 methods)

### Calculate KE and T

In [14]:
function calc_KE(V, N, m =1)
    KE = 0.
    T = 0.
    for p in eachrow(V)
        v_squared = sum(p.^2) #get squared magnitude of velocity vector
        KE += 0.5(m*v_squared) #accumulate KE for each particle
        T += v_squared/(3N-3)
    end
    return KE, T 
end

calc_KE (generic function with 2 methods)

### LD Simulation

In [152]:
function LD(T, dt, iters, R=initR())

    N = length(R[:,1]) #number of particles
    V = init_velocity(T,N) #velocity for t
    A = zeros(N,3,3) #acceleration matrix
    
    PE = Vector{Float64}(undef,iters+1) #initialize array of potential energies 
    return fvector = update_A(R,T,V,dt) #initialize acceleration matrix and return initial PE

    PE[1], A = update_A(A,R,T,V,dt) #initialize acceleration matrix and return initial PE
    

    KE = Vector{Float64}(undef,iters+1) #initialize array of kinetic energies 
    KE[1], = calc_KE(V,N) #initial KE 

    T_list = Vector{Float64}(undef,iters+1) #initialize array of kinetic energies 
    T_list[1] = T #initial temperature


    for i in 1:iters
        curr_A = sum(copy(A),dims=3) #A for current t
        update_R!(R,V,curr_A,dt) #new R updated to t+dt
        PE[i+1],A = update_A(R,T,V,dt) #new A updated in-place to t+dt, and returns PE into array 
        update_V!(V,curr_A,A,dt) #new V updated to t+dt
        KE[i+1],T_list[i+1] = calc_KE(V,N) #add KE
        # T_list[i+1] = calc_T(KE[i+1],kb,N) #add T
    end
    return  PE, KE, T_list, A, V, R 
end

LD (generic function with 2 methods)

In [153]:
# Random.seed!(1234)
PE, KE, T_list, A, V, R= LD(2.,0.003,10000)

LoadError: MethodError: no method matching update_A(::Matrix{Float64}, ::Float64, ::Matrix{Float64}, ::Float64)
Closest candidates are:
  update_A(::Any, ::Any, ::Any, ::Any, ::Any) at In[149]:1
  update_A(::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at In[149]:1

In [47]:
fvector = LD(2.,0.003,10000)

3-element Vector{Vector{Float64}}:
 [0.0, 0.0, -0.0]
 [0.0, 0.0, -0.0]
 [0.0, 0.0, -0.0]